# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 866aa8c168c703d074bbf5d6ecead6047cac2029df2ab883696e0dd88d7f95047a11499a8531c7b425de554e04d6cf42c9e3be080d9dfc6491787448082ecdbf

test:
  secret_key_base: 3dcd41f8152d1ca9636947fb3d32043091f74a2227ad02421eab792d3ee781b97fcf42a25c50187407ff2342de297cd1826ac40d24cf7f06d395e087ffc161f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
